"""new fields in user model

Revision ID: 150ab6dbe0bc
Revises: 92614b46cd94
Create Date: 2022-03-16 16:08:12.258364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150ab6dbe0bc'
down_revision = '92614b46cd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
